site_name: pyCHIPS Documentation
repo_url: https://github.com/shibaji7/pyCHIPS
theme: 
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
    - search
    - glightbox
    - bibtex:
        bib_file: "docs/refs.bib"
    - mkdocstrings:
        enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
        custom_templates: templates
        default_handler: python
        handlers:
          python:
            options:
              show_source: true
     
markdown_extensions:
    - extra
    - admonition
    - toc
    - attr_list
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - footnotes
        
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Installation: user/install.md  
    - JSOC Data Access: user/jsoc.md 
    - Citing: user/citing.md
    - Tutorials: 
            - Objectives: tutorial/objectives.md
            - How it Works?: tutorial/workings.md
            - Open Flux Problem: tutorial/openflux.md
            - Example Event: tutorial/example.md
    - Code Documentation: 
            - Fetch Maps: dev/fetch.md
            - CHIPS Tools: dev/chips.md
            - Plotting Tools: dev/plots.md